$(document).ready(function(){
  $("svg:nth-child(1)").hover(function(){
    $(".indicator").css("margin-top","8%");
  })
  $("svg:nth-child(2)").hover(function(){
    $(".indicator").css("margin-top","16%");
  })
  $("svg:nth-child(3)").hover(function(){
    $(".indicator").css("margin-top","24%");
  })
});
